baseURL = "https://vantiscpa.com/"
languageCode = "en-us"
title = "Vantis CPA"
pluralizeListTitles = false
disableKinds = ["taxonomy", "term"]
enableGitInfo = true

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
page = ["HTML"]

[params]
description = "Tax consulting for founders, expats, and global businesses"

[markup.goldmark.renderer]
unsafe = true

[minify]
minifyOutput = true
