baseURL = "https://vantiscpa.com/"
languageCode = "en-us"
title = "Vantis CPA"
pluralizeListTitles = false
disableKinds = ["taxonomy", "term"]

[params]
description = "Tax consulting for founders, expats, and global businesses"

[markup.goldmark.renderer]
unsafe = true

[minify]
minifyOutput = true
